/** explainer-kit: the narrated-explanation → guided-play → exercise engine, style-agnostic (a style plugs in as a View). */
export { AudioClock, ManualClock, PerfClock, type Clock } from './core/clock';
export { clamp, lerp, smooth, damp, rng, numbers } from './core/math';
export { LearnerStore, LocalStorage, MemoryStorage, PROGRESS_KEY, type Saved, type UnitProgress, type Prefs, type Storage } from './core/store';
export { Events, type Progress } from './core/events';
export type { Word, Clip, CueSheet, Term, UnitSpec, UnitBundle, ChapterSpec, PartSpec, ClipSpec, ExerciseSpec, MisconceptionSpec } from './content/types';
export { loadBundle } from './content/load';
export { lintUnit } from './content/lint';
export { CueBinder, layoutClips } from './motion/cues';
export { Timeline } from './motion/timeline';
export { VoicePlayer, NullVoice, type Voice, type Earcon, type Bus } from './audio/voice';
export { Captions, spanAt, type Span, type Token } from './captions';
export { OnDemand, stateKey } from './loop';
export { Spring } from './play/spring';
export { DetentHand, type DialGeom, type Hand } from './play/hand';
export { SlideHand, type Track } from './play/slide';
export { SlotHand, type Seats } from './play/slots';
export { LockedHand } from './play/locked';
export { PointerRouter, SLOP, type Projector, type Grabbable } from './play/pointer';
export { HotspotRouter, disc, box, type Hotspot } from './play/hotspots';
export { MarkerRouter, MARKER_HIT, MARKER_SLACK, partMarkers, type Marker } from './play/markers';
export { discOf, boxOf, segOf, around, dist, overlaps, segHits, edgePoint, centre, contains, within, mapShape, type Shape } from './place/shapes';
export { place, put, layoutFaults, pairFaults, offEdge, clipped, ring, beside, RULES as LAYOUT_RULES, type Entity, type Item, type Kind, type Rules } from './place/place';
export { bindKeys, pressKey, keyHint, KEYS, type KeyTarget, type KeyActions } from './play/keys';
export type { View, ShellPort, UnitDef, Control, Live, Working, Explained, NamedTerm, EndCard, ButtonKind } from './unit/ports';
export { TermIndex } from './unit/terms';
export { sectionOf, sectionView, lessonPoint, type SectionSpec, type SectionView } from './unit/sections';
export { SectionHead } from './shell/section';
export { chapterList, chapterSpecs, chapterAt, type Chapter } from './unit/chapters';
export { track, restore, resumeLine, isFinished, landing, type TrackOptions, type ResumePoint, type Tracker, type StopPoint, type BeginChoice, type BeginOffer, type FinishedOffer } from './unit/resume';
export { Director, type DirectorParts, type Easing } from './unit/director';
export { BeatMachine, type Beat, type EnterOptions, type LabelMode } from './unit/beats';
export { WatchBeat, type WatchOptions } from './unit/watch';
export { GuidedPlay, all, settled, handAt, type Spec, type GuidedStep, type GuidedOptions } from './unit/guided';
export { Exercise, type Round, type ExerciseOptions } from './unit/exercise';
export { EndBeat, type EndOptions } from './unit/end';
export { CommandLog, type Command } from './unit/log';
export { BenchFlow, FLOW, type FlowRules, type Firing } from './unit/flow';
export { HintLadder, type Rung } from './unit/hints';
export { Walk, type WalkStep } from './unit/walk';
export { Bench, type Task, type BenchOptions, type Judged } from './unit/bench';
export { KindRegistry, KINDS, lintPlay, type ExerciseKind, type AnswerSpace, type PlayCode } from './unit/kinds';
export { Shell, type ShellText, type ShellActions } from './shell/shell';
export { Pops, type PopKind, type SectionEntry } from './shell/pops';
export { Player } from './player';
export { boot, probe, type BootOptions, type Probe } from './boot';
